### ISSUE TITLE
Parameters not found

### ISSUE THREAD

**Issue by mehrezsamir** [kachkaev/KachkaevAssetsVersionBundle#7]
The service "kachkaev_assets_version.assets_version_manager" has a dependency on a non-existent parameters "kachkaev_assets_version.filename" and "kachkaev_assets_version.parametername".
It must be "kachkaev_assets_version.file_path" and "kachkaev_assets_version.parameter_name".

ParameterNotFoundException: The service "kachkaev_assets_version.assets_version_manager" has a dependency on a non-existent parameter "kachkaev_assets_version.filename". Did you mean one of these: "kachkaev_assets_version.file_path", "kachkaev_assets_version.parameter_name"?

**Comment by kachkaev** [comment]
Hi @mehrezsamir,

Could you please update the bundle to version 2.0.1 and confirm that the issue has been resolved? Sorry for the inconvenience – this is a result of a late-night release :–)

**Comment by mehrezsamir** [comment]
Hi @kachkaev,

Thanks you, the issue has been resolved and actualy all is well.
thank you for this work and good continuation :+1:
